# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JankenApp01' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JankenApp01
  pod 'SVProgressHUD'
end
