# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GetQiitaApi002' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GetQiitaApi002
  pod 'SwiftyJSON'
  pod 'Alamofire'

  target 'GetQiitaApi002Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GetQiitaApi002UITests' do
    # Pods for testing
  end

end
